name: "SurrealDB in Github Actions"
description: "Start a SurrealDB instance in Github Actions"

branding:
  icon: "database"
  color: "purple"

inputs:
  surrealdb_version:
    description: "The version of SurrealDB to use, default is latest"
    required: false
    default: "latest"
  surrealdb_port:
    description: "The port to run SurrealDB on, default is 8000"
    required: false
    default: "8000"
  surrealdb_username:
    description: "The username to use for SurrealDB"
    required: false
  surrealdb_password:
    description: "The password to use for SurrealDB"
    required: false
  surrealdb_auth:
    description: "Enable authentication for SurrealDB"
    required: false
    default: "false"
  surrealdb_strict:
    description: "Enable strict mode for SurrealDB"
    required: false
    default: "false"
  surrealdb_log:
    description: "Enable logs printed out in the console."
    required: false
  surrealdb_additional_args:
    description: "Additional arguments to pass to SurrealDB"
    required: false
# runs:
#   using: "docker"
#   image: "Dockerfile"
#   args:
#     - ${{ inputs.surrealdb_version }}
#     - ${{ inputs.surrealdb_port }}
#     - ${{ inputs.surrealdb_username }}
#     - ${{ inputs.surrealdb_password }}
#     - ${{ inputs.surrealdb_auth }}
#     - ${{ inputs.surrealdb_strict }}
#     - ${{ inputs.surrealdb_log }}
#     - ${{ inputs.surrealdb_additional_args }}
#   env:
#     SURREALDB_VERSION: ${{ inputs.surrealdb_version }}
#     SURREALDB_PORT: ${{ inputs.surrealdb_port }}
runs:
  using: composite
  steps:
    - name: Install SurrealDB
      shell: bash
      run: curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh -s -- --version ${{ inputs.surrealdb_version }}

    - name: Run SurrealDB in Background
      shell: bash
      run: |
        cd /usr/local/bin
        nohup surreal start \
          -u ${{ inputs.surrealdb_username }} \
          -p ${{ inputs.surrealdb_password }} \
          --allow-all &
        
    - name: Wait for SurrealDB to start
      shell: bash
      run: |
        URL="http://localhost:8000/health"
        MAX_ATTEMPTS=30
        ATTEMPT=0

        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
            
            if [ "$RESPONSE" -eq 200 ]; then
                echo "SurrealDB instance is up and running, continuing..."
                break
            fi
            
            ATTEMPT=$((ATTEMPT + 1))
            sleep 1
        done

        if [ "$ATTEMPT" -ge "$MAX_ATTEMPTS" ]; then
            echo "SurrealDB instance could not be contacted, aborting."
            exit 1
        fi