name: Run Action

on:
  workflow_dispatch:
  push:
    branches: [main, change/action-improvements]
  pull_request:
    branches: [main]

jobs:
  surrealdb-setup:
    runs-on: ubuntu-latest

    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Action
        uses: ./

      - name: Check background task is running
        run: |
          if ps -p $(cat /tmp/surreal.pid) > /dev/null; then
            echo "SurrealDB service is running."
          else
            echo "SurrealDB service is not running."
          fi

      - name: Retrieve SurrealDB version
        run: curl http://127.0.0.1:8000/version