name: Push Release

on:
  release:
    types: [published]

permissions: 
  contents: write

jobs:

  ci:
    name: CI Job
    uses: ./.github/workflows/ci.yml

  update_tag:
    name: Update Tag Job
    runs-on: ubuntu-latest
    needs: [ci]
    permissions: 
      contents: write
    steps:
      - name: Update the ${{ github.event.release.tag_name }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}